#!/usr/bin/env node
/**
 * scripts/init.mjs
 *
 * Interactive first-run setup: validates environment, helps the user
 * populate `.env.local` (API keys + Notion connection), verifies Notion
 * if configured, and prints KB setup guidance. Skips the build step —
 * `npm run desktop:build` remains the canonical app-install command.
 */

import { chmod, mkdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';

import { envLocalPath, repoRoot } from './lib/paths.mjs';
import { confirm, input, select } from './lib/prompt.mjs';
import { checkNode, checkNotion, readEnvLocal } from './lib/checks.mjs';
import { runStreaming } from './lib/proc.mjs';

const FLAGS = {
  yes: process.argv.includes('--yes'),
};

if (process.env.CI && !FLAGS.yes) {
  console.error('[init] Refusing to run interactively in CI. Pass --yes to bypass.');
  process.exit(1);
}

const RECOMMENDED_KEYS = [
  { key: 'GEMINI_API_KEY', label: 'Google Gemini', optional: true, masked: true },
  { key: 'OPENAI_API_KEY', label: 'OpenAI', optional: true, masked: true },
  { key: 'ANTHROPIC_API_KEY', label: 'Anthropic', optional: true, masked: true },
  { key: 'NOTION_API_KEY', label: 'Notion integration token', optional: true, masked: true },
  { key: 'RAMBLE_NOTION_ROOT', label: 'Notion root page UUID', optional: true, masked: false },
];

const renderEnvFile = (entries) => {
  const lines = [
    '# Ramble On — local environment',
    '# Generated by scripts/init.mjs. Edit freely; lines starting with # are ignored.',
    '',
  ];
  for (const [key, value] of Object.entries(entries)) {
    if (value == null || value === '') continue;
    lines.push(`${key}=${value}`);
  }
  lines.push('');
  return lines.join('\n');
};

const printNotionInstructions = () => {
  console.log(`
Notion KB setup (manual; one-time):

  1. Create a Notion internal integration:
     https://www.notion.so/my-integrations → "+ New integration" → copy the
     "Internal Integration Secret" → paste here as NOTION_API_KEY.

  2. Pick or create the page Ramble On should treat as the KB root.
     Copy its 32-char UUID from the URL (the trailing hex string) → paste
     here as RAMBLE_NOTION_ROOT.

  3. Open the root page in Notion, click the "..." menu →
     "Connect to" → choose your integration. Without this, the API can
     authenticate but cannot read the page (verify will return 404).

  4. Optional: under the root, create a subpage titled "Voice Model" so
     ramble.get_voice_model can find it (see notion-client.cjs:215-233).

  Note: Ramble On uses whatever pages your integration is shared with —
  the script does not expand or modify access. To add more, share more
  pages with the same integration in Notion.
`);
};

const printKbMigrationNote = () => {
  console.log(`
Heads-up: when packaged, the app reads/writes Knowledge Base files at
  ~/Library/Application Support/ramble_on/kb
NOT the repo's ./kb directory. The repo's kb/ is bundled into the .app
asar but not auto-copied to userData on first launch (see
electron/main.cjs:228-231). If you have notes in ./kb that you want the
installed app to see, copy them into the userData kb/ manually.
`);
};

const ensureNodeModules = async () => {
  if (existsSync(`${repoRoot}/node_modules`)) return;
  if (!FLAGS.yes) {
    const proceed = await confirm(
      'node_modules/ is missing. Run `npm install` now?',
      { defaultValue: true },
    );
    if (!proceed) {
      console.log('[init] Skipping npm install. The app will not build until you run it.');
      return;
    }
  }
  await runStreaming('npm', ['install'], { cwd: repoRoot });
};

const collectKey = async (current, def) => {
  const existing = current[def.key];
  if (existing) {
    if (FLAGS.yes) return existing;
    const reuse = await confirm(
      `Keep existing ${def.label} (${def.key})?`,
      { defaultValue: true },
    );
    if (reuse) return existing;
  }
  const value = await input(
    `Enter ${def.label} (${def.key})${def.optional ? ' [press enter to skip]' : ''}`,
    { defaultValue: '', mask: def.masked, assumeYes: FLAGS.yes },
  );
  return value || existing || '';
};

const collectProvider = async (current) => {
  if (FLAGS.yes) return current.AI_PROVIDER || 'gemini';
  const choice = await select(
    'Which AI provider should Ramble On use by default?',
    [
      { value: 'gemini', label: 'Google Gemini (also handles video gen)' },
      { value: 'openai', label: 'OpenAI' },
      { value: 'anthropic', label: 'Anthropic' },
    ],
    { defaultIndex: ['gemini', 'openai', 'anthropic'].indexOf(current.AI_PROVIDER || 'gemini') },
  );
  return choice || 'gemini';
};

const main = async () => {
  console.log('Ramble On — init\n');

  const node = await checkNode();
  if (!node.ok) {
    console.error(`[init] Node ${node.label} — ${node.detail}`);
    process.exit(1);
  }

  await ensureNodeModules();

  const current = (await readEnvLocal()) ?? {};
  const next = { ...current };

  if (Object.keys(current).length === 0) {
    console.log('No .env.local found — creating one.\n');
  } else {
    console.log(`Found existing .env.local with ${Object.keys(current).length} key(s).\n`);
  }

  next.AI_PROVIDER = await collectProvider(current);

  for (const def of RECOMMENDED_KEYS) {
    next[def.key] = await collectKey(current, def);
  }

  const hasTextProvider = ['GEMINI_API_KEY', 'OPENAI_API_KEY', 'ANTHROPIC_API_KEY'].some(
    (k) => next[k],
  );
  if (!hasTextProvider) {
    const proceed = FLAGS.yes
      ? true
      : await confirm(
          'No text-provider API key set. Continue anyway?',
          { defaultValue: false },
        );
    if (!proceed) {
      console.log('[init] Aborted. Re-run when you have at least one API key.');
      process.exit(1);
    }
  }

  await mkdir(repoRoot, { recursive: true });
  await writeFile(envLocalPath(), renderEnvFile(next), 'utf8');
  await chmod(envLocalPath(), 0o600);
  console.log(`\n[init] Wrote ${envLocalPath()} (mode 0600).\n`);

  if (next.NOTION_API_KEY && next.RAMBLE_NOTION_ROOT) {
    console.log('[init] Verifying Notion connection...');
    process.env.NOTION_API_KEY = next.NOTION_API_KEY;
    process.env.RAMBLE_NOTION_ROOT = next.RAMBLE_NOTION_ROOT;
    const notionResult = await checkNotion();
    const marker = notionResult.ok ? 'PASS' : 'FAIL';
    console.log(`  [${marker}] notion: ${notionResult.label} — ${notionResult.detail}`);
    if (!notionResult.ok) {
      console.log('[init] Notion verification failed. See message above.');
      printNotionInstructions();
    }
  } else if (next.NOTION_API_KEY || next.RAMBLE_NOTION_ROOT) {
    console.log(
      '[init] Need both NOTION_API_KEY and RAMBLE_NOTION_ROOT for Notion-backed KB. ' +
        'Re-run init when you have both.',
    );
    printNotionInstructions();
  } else {
    console.log(
      '[init] Notion not configured — Ramble On will run in standalone mode ' +
        '(KB lives only on disk).',
    );
    printNotionInstructions();
  }

  printKbMigrationNote();

  console.log('Next steps:');
  console.log('  npm run desktop:build      # build the .app');
  console.log('  npm run app:update         # install/replace /Applications/Ramble On.app');
  console.log('  npm run app:doctor         # diagnose at any time');
};

main().catch((error) => {
  console.error('[init] fatal:', error);
  process.exit(2);
});
